import Head from 'next/head';
import FlightCard from '@/components/Flight';

import flights from '../datas/flights.json';

export default function Home() {

  return (
    <>
      <Head>
        <title>Airplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container flex flex-col gap-4 mx-auto py-8'>
        <h1 className='text-2xl'>Dev Airplace - All tickets</h1>

        <div className="flex flex-col gap-4">
          {flights.map((flight, key) => {
            return (
              <div key={key}>
                <FlightCard flight={flight} />
              </ div>
            )
          })}

        </div>

      </div>
    </>
  );
}
